### ISSUE TITLE
Small issue with TIP

### ISSUE THREAD

**Issue by yumyo** [zanfab/docsify-plugin-flexible-alerts#2]
Hi,
I have just noticed that, at least using themeable, the Tip callout has more padding and two icons. Please see the screenshot below.

### Before

![image](https://user-images.githubusercontent.com/959034/51329740-0ee31a80-1a6e-11e9-87a6-5556a9e799f8.png)

Temporarily solving the issue is as simple as adding:

```css
.markdown-section .tip:before {
	content: unset;
}

.markdown-section .tip {
	padding: .75rem 1.25rem;
}
```

### After

![image](https://user-images.githubusercontent.com/959034/51329802-29b58f00-1a6e-11e9-873c-a1fd1dd927ba.png)
